apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: celery-worker
  namespace: studtarasov
  annotations:
    description: "Deployment of the graph learning workbench"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: celery-worker
    spec:
      containers:
      - resources:
          limits:
            nvidia.com/gpu: "1"
            cpu: "4"
            memory: "8Gi"
          requests:
            nvidia.com/gpu: "1"
            cpu: "4"
            memory: "8Gi"
        name: celery-worker
        image: ls6-stud-registry.informatik.uni-wuerzburg.de/studtarasov/graph_learning_workbench:0.0.1
        imagePullPolicy: "Always"
        env:
          - name: REDIS_HOST
            value: "redis-master"
          - name: REDIS_PORT
            value: "6379"
          - name: RABBITMQ_HOST
            value: "rabbitmq-service"
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USER
            value: "guest"
          - name: RABBITMQ_PASSWORD
            value: "guest"
          - name: MLFLOW_URI
            value: "/mlflow"
          - name: USERNAME
            value: 1317
        command: ["celery", "-A", "task_manager.tasks", "worker", "--concurrency", "4"]
        volumeMounts:
          - mountPath: /workspace
            name: project-code-for-celery
          - mountPath: /mlflow
            name: celery-mlflow-volume
      priorityClassName: "research-high"
      imagePullSecrets:
      - name: lsx-registry
      restartPolicy: "Always"
      volumes:
        - name: project-code-for-celery
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studtarasov
            path: "/home/stud/tarasov/xtai_lab3/application"
            secretRef:
              name: ceph-secret
        - name: celery-mlflow-volume
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studtarasov
            path: "/home/stud/tarasov/xtai_lab3/mlflow"
            secretRef:
              name: ceph-secret