import { Metadata } from "../definitions/network";
import { Task } from "../definitions/task";

export const metadataConverter = {
  toFirestore: function (metadata: Metadata) {
    return {
      id: metadata.id,
      name: metadata.name,
      description: metadata.description,
      color: metadata.color,
    };
  },
  fromFirestore: function (snapshot, options) {
    const data = snapshot.data(options);
    return new Metadata(data.id, data.name, data.description, data.color);
  },
};

export const tasksConverter = {
  toFirestore: function (task: Task) {
    return {
      // id will be generated by firestore
      mlModelType: task.mlModelType,
      taskType: task.taskType,
      epochs: task.epochs,
      train_percentage: task.trainPercentage,
      learning_rate: task.learningRate,
      hidden_layer_sizes: task.hiddenLayerSizes,
      seed: task.seed,
    };
  },
  fromFirestore: function (snapshot, options) {
    const data = snapshot.data(options);
    return new Task(
      data.id,
      data.mlModelType,
      data.taskType,
      data.epochs,
      data.train_percentage,
      data.learning_rate,
      data.hidden_layer_sizes,
      data.seed
    );
  },
};
