apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: graph-learning-workbench
  namespace: studtarasov
  annotations:
    description: "Deployment of the graph learning workbench"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: graph-learning-workbench
    spec:
      containers:
      - resources:
          limits:
            cpu: "4"
            memory: "8Gi"
          requests:
            cpu: "4"
            memory: "8Gi"
        name: graph-learning-workbench
        image: ls6-stud-registry.informatik.uni-wuerzburg.de/studtarasov/graph_learning_workbench:0.0.1
        imagePullPolicy: "Always"
        env:
          - name: REDIS_HOST
            value: "redis-master"
          - name: REDIS_PORT
            value: "6379"
          - name: RABBITMQ_HOST
            value: "rabbitmq-service"
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_USER
            value: "guest"
          - name: RABBITMQ_PASSWORD
            value: "guest"
        command: ["uvicorn", "app:create_app", "--factory", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
        ports:
        - name: http
          containerPort: 8000
        volumeMounts:
          - mountPath: /workspace
            name: project-code
      priorityClassName: "research-med"
      imagePullSecrets:
      - name: lsx-registry
      restartPolicy: "Always"
      volumes:
        - name: project-code
          cephfs:
            monitors:
              - 132.187.14.16,132.187.14.17,132.187.14.19,132.187.14.20
            user: studtarasov
            path: "/home/stud/tarasov/xtai_lab3/application"
            secretRef:
              name: ceph-secret