export const enum FetchableAccordionState {
    ACCORDION_CLOSED,
    FETCHING,
    UPLOADING,
    FETCH_ERROR,
    UPLOAD_ERROR,
    FETCHED,
    UPLOADED,
    NETWORK_EXISTS,
    SHOW_MULTIPLE_NETWORK,
    HIDE_MULTIPLE_NETWORK
}
  